import re,tkinter,socket,requests,urllib3
from bs4 import BeautifulSoup
from tkinter import Tk
root=Tk()
root.title('website informer ')
def code():
    inp = entry.get()
    a = requests.get(inp)
    urls = urllib3.get_host(inp)
    ip = socket.gethostbyname(urls[1])
    # print(a.apparent_encoding)
    # socket
    dns = socket.getfqdn(urls[1])
    p = socket.gethostbyaddr(ip)
    # content
    text = a.text
    ref = []
    ref2 = []
    soap = BeautifulSoup(text, 'lxml')
    for links in soap.find_all('a'):
        liks = links.get('href')
        ref.append(liks)
    for refs in soap.find_all('href'):
        ref2.append(refs)
    pri = re.sub('\n', ' ', soap.text)
    textbox.insert(tkinter.INSERT,'The status code of the website is ')
    textbox.insert(tkinter.INSERT, '\n')
    textbox.insert(tkinter.INSERT,a.status_code)
    textbox.insert(tkinter.INSERT,'\n')
    textbox.insert(tkinter.INSERT, '\n')
    textbox.insert(tkinter.INSERT,'the Ip of the website is ')
    textbox.insert(tkinter.INSERT, '\n')
    textbox.insert(tkinter.INSERT,ip)
    textbox.insert(tkinter.INSERT, '\n')
    textbox.insert(tkinter.INSERT, '\n')
    textbox.insert(tkinter.INSERT,'The headers related to the websites are ')
    textbox.insert(tkinter.INSERT, '\n')
    textbox.insert(tkinter.INSERT,a.headers)
    textbox.insert(tkinter.INSERT, '\n')
    textbox.insert(tkinter.INSERT, '\n')
    textbox.insert(tkinter.INSERT,'The dns related to the website is ')
    textbox.insert(tkinter.INSERT, '\n')
    textbox.insert(tkinter.INSERT,dns)
    textbox.insert(tkinter.INSERT, '\n')
    textbox.insert(tkinter.INSERT, '\n')
    textbox.insert(tkinter.INSERT,'The links related to website is ')
    textbox.insert(tkinter.INSERT, '\n')
    for j in ref:
        textbox.insert(tkinter.INSERT,j)
    textbox.insert(tkinter.INSERT, '\n')
    textbox.insert(tkinter.INSERT, '\n')
    textbox.insert(tkinter.INSERT, 'The links related to website is ')
    textbox.insert(tkinter.INSERT, '\n')
    for i in ref2:
        textbox.insert(tkinter.INSERT,i)
    textbox.insert(tkinter.INSERT, '\n')
    textbox.insert(tkinter.INSERT, '\n')
    textbox.insert(tkinter.INSERT, 'The ip related to dns is ')
    textbox.insert(tkinter.INSERT, '\n')
    textbox.insert(tkinter.INSERT,p)
    textbox.insert(tkinter.INSERT, '\n')
    textbox.insert(tkinter.INSERT, '\n')
    textbox.insert(tkinter.INSERT, 'The content related to website is  ')
    textbox.insert(tkinter.INSERT, '\n')
    textbox.insert(tkinter.INSERT,pri)
    textbox.insert(tkinter.INSERT, '\n')
    textbox.insert(tkinter.INSERT, '\n')
    textbox.config(state='disabled')
def clear():
    textbox.config(state=tkinter.NORMAL)
    textbox.delete(1.0,tkinter.END)
lbl=tkinter.Label(root,text='welcome to the website informer')
lbl.pack(pady=5)
entry=tkinter.Entry(root,width=40)
entry.pack(pady=5)
btn=tkinter.Button(root,width=20,text='search',command=code)
btn.pack(pady=5)
btn2=tkinter.Button(root,width=20,text='clear' ,command=clear)
btn2.pack(pady=5)
textbox=tkinter.Text(root,width=150,height=95)
textbox.pack(pady=5)
root.mainloop()
